### local ###
spring:
  profiles:
    active: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/base?serverTimezone=UTC&characterEncoding=UTF-8
    username: 아이디
    password: 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

# thymeleaf에 대한 설정을 합니다.
  thymeleaf:
    check-template-location: true
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
  
mybatis:
  type-aliases-package: com.cons
  mapper-locations: mybatis/mapper/**/*.xml
  
# API 호출 시, SQL 문을 콘솔에 출력
  jpa:
    show-sql: true
    # DDL 정의시 데이터베이스의 고유 기능을 사용
    # ex) 테이블 생성, 삭제 등
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update 